spring:
    application:
        name: urly
    datasource:
        url: jdbc:h2:mem:urlydb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
management:
    endpoints:
        web:
            exposure:
                include:
                - health
                - info
                - prometheus

urly:
    shortener:
        md5:
            size: 10
        max-collision-attempts: 10